export const blogPlansCopy = {
  ko: {
    title: '블로그 콘텐츠 기획',
    description: '카테고리별 기존 글과 활성 기획의 제목, slug, 설명만 참고해 새 기획 후보를 생성합니다.',
    back: '글 목록',
    generate: '기획 후보 생성',
    generating: '생성 중',
    saveSelected: '선택 저장',
    saving: '저장 중',
    category: '카테고리',
    count: '후보 개수',
    provider: '생성 모델',
    seedKeywords: '포함 키워드',
    excludedTopics: '제외 주제',
    audience: '대상 독자',
    direction: '콘텐츠 방향',
    candidateTitle: '생성 후보',
    listTitle: '저장된 기획',
    filterActive: 'Active',
    filterReady: 'Ready',
    filterPublished: 'Published',
    filterAll: 'All',
    emptyCandidates: '아직 생성된 후보가 없습니다.',
    emptyPlans: '저장된 기획이 없습니다.',
    context: '참고 컨텍스트',
    posts: '기존 글',
    activePlans: '활성 기획',
    generated: '생성 결과 있음',
    notGenerated: '미생성',
    generatePost: 'Generate',
    publishPost: 'Publish',
    deletePlan: 'Delete',
    regeneratePost: '재생성',
    postGenerating: '생성 중',
    postPublishing: '발행 중',
    planDeleting: '삭제 중',
    postModel: '글 모델',
    postPrompt: '글 프롬프트',
    customPrompt: '커스텀',
    promptButton: 'PROMPT',
    promptList: '프롬프트 목록',
    promptTitle: '프롬프트 제목',
    promptContent: '프롬프트 내용',
    newPrompt: '새 프롬프트',
    savePrompt: '프롬프트 저장',
    deletePrompt: '프롬프트 삭제',
    promptDeleted: '프롬프트가 삭제되었습니다.',
    promptSettings: '프롬프트 편집',
    draftPrompt: '원고 생성 프롬프트',
    jsonPrompt: 'JSON 변환 프롬프트',
    savePrompts: '프롬프트 저장',
    resetPrompts: '기본값',
    promptSaved: '프롬프트가 저장되었습니다.',
    promptReset: '기본 프롬프트로 되돌렸습니다.',
    promptLoadError: '글 생성 프롬프트를 불러오지 못했습니다.',
    promptSaveError: '프롬프트 저장에 실패했습니다.',
    promptResetError: '프롬프트 초기화에 실패했습니다.',
    promptDeleteError: '프롬프트 삭제에 실패했습니다.',
    postGenerated: '글 생성 결과를 저장했습니다.',
    postGenerateError: '글 생성에 실패했습니다.',
    postPublished: '블로그 글을 발행했습니다.',
    postPublishError: '블로그 글 발행에 실패했습니다.',
    planDeleted: '기획을 삭제했습니다.',
    planDeleteError: '기획 삭제에 실패했습니다.',
    planDeleteConfirm: '이 기획을 삭제할까요? 생성된 payload도 함께 삭제됩니다.',
    linked: '연결 글',
    noCategory: '카테고리 없음',
    saved: (count: number) => `${count}개 기획을 저장했습니다.`,
    selectCategory: '카테고리를 선택해 주세요.',
    selectCandidates: '저장할 후보를 선택해 주세요.',
  },
  en: {
    title: 'Blog Content Plans',
    description: 'Generate new plan candidates using only title, slug, and description from the selected category.',
    back: 'Posts',
    generate: 'Generate Plans',
    generating: 'Generating',
    saveSelected: 'Save Selected',
    saving: 'Saving',
    category: 'Category',
    count: 'Count',
    provider: 'Provider',
    seedKeywords: 'Seed keywords',
    excludedTopics: 'Excluded topics',
    audience: 'Audience',
    direction: 'Direction',
    candidateTitle: 'Candidates',
    listTitle: 'Saved plans',
    filterActive: 'Active',
    filterReady: 'Ready',
    filterPublished: 'Published',
    filterAll: 'All',
    emptyCandidates: 'No candidates generated yet.',
    emptyPlans: 'No saved plans yet.',
    context: 'Context',
    posts: 'Posts',
    activePlans: 'Active plans',
    generated: 'Generated payload',
    notGenerated: 'Not generated',
    generatePost: 'Generate',
    publishPost: 'Publish',
    deletePlan: 'Delete',
    regeneratePost: 'Regenerate',
    postGenerating: 'Generating',
    postPublishing: 'Publishing',
    planDeleting: 'Deleting',
    postModel: 'Post model',
    postPrompt: 'Post prompt',
    customPrompt: 'Custom',
    promptButton: 'PROMPT',
    promptList: 'Prompts',
    promptTitle: 'Prompt title',
    promptContent: 'Prompt content',
    newPrompt: 'New prompt',
    savePrompt: 'Save prompt',
    deletePrompt: 'Delete prompt',
    promptDeleted: 'Prompt deleted.',
    promptSettings: 'Edit prompts',
    draftPrompt: 'Draft prompt',
    jsonPrompt: 'JSON prompt',
    savePrompts: 'Save prompts',
    resetPrompts: 'Default',
    promptSaved: 'Prompts saved.',
    promptReset: 'Restored default prompts.',
    promptLoadError: 'Could not load post prompts.',
    promptSaveError: 'Failed to save prompts.',
    promptResetError: 'Failed to reset prompts.',
    promptDeleteError: 'Failed to delete prompt.',
    postGenerated: 'Generated payload saved.',
    postGenerateError: 'Failed to generate post.',
    postPublished: 'Blog post published.',
    postPublishError: 'Failed to publish post.',
    planDeleted: 'Plan deleted.',
    planDeleteError: 'Failed to delete plan.',
    planDeleteConfirm: 'Delete this plan? The generated payload will also be deleted.',
    linked: 'Linked post',
    noCategory: 'No category',
    saved: (count: number) => `Saved ${count} plans.`,
    selectCategory: 'Choose a category.',
    selectCandidates: 'Choose candidates to save.',
  },
};

export type BlogPlansLanguage = keyof typeof blogPlansCopy;
export type BlogPlansCopy = typeof blogPlansCopy[BlogPlansLanguage];

export const blogPlanStatusStyles: Record<string, string> = {
  pending: 'bg-amber-50 text-amber-700 ring-1 ring-amber-200 dark:bg-amber-500/10 dark:text-amber-300 dark:ring-amber-800',
  generating: 'bg-blue-50 text-blue-700 ring-1 ring-blue-200 dark:bg-blue-500/10 dark:text-blue-300 dark:ring-blue-800',
  ready: 'bg-emerald-50 text-emerald-700 ring-1 ring-emerald-200 dark:bg-emerald-500/10 dark:text-emerald-300 dark:ring-emerald-800',
  published: 'bg-zinc-100 text-zinc-700 ring-1 ring-zinc-200 dark:bg-zinc-800 dark:text-zinc-200 dark:ring-zinc-700',
  paused: 'bg-orange-50 text-orange-700 ring-1 ring-orange-200 dark:bg-orange-500/10 dark:text-orange-300 dark:ring-orange-800',
  discarded: 'bg-red-50 text-red-700 ring-1 ring-red-200 dark:bg-red-500/10 dark:text-red-300 dark:ring-red-800',
};
